#+title: Main

* Introduction
We aim to apply machine learning techniques to analysis of /network flows/ as generated by Zeek. To this end, [[../scripts/my_analysis.py]] exists as a method to extract relevant logs from PCAP files. The rationale behind this is that packets aren't particularly useful in isolation  - a single packet can't really indicate a DDoS for example but a thousand packets from the same origin could. Zeek outputs a lot of different files that cuts down on analysis time. By default it outputs to [[../logs]].

The other useful script I made is [[../scripts/attack.py]], which automates a lot (but not all) of the data gathering stuff. I didn't think about it at the time, but I could have better automated the setting of a virtual machine, but alas. Currently, it'll run ~tcpdump~ on the target IP address (i.e. we're assuming you have access to it), and then gives you a convenient interface to run whatever attack in whatever order you want, as well some semblance of simulating normal traffic.
